---
title: Stalwartmc.Github.Io
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
Navigation:
  Home: "/"
  About Us: aboutus.markdown
  Services: services.markdown
  Industries: industries.markdown
  Clients: clients.markdown
  Contact Us: contactus.markdown
